# Generated by Django 2.0.5 on 2018-06-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20180604_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='is_killed',
            field=models.BooleanField(default=False),
        ),
    ]
