# Generated by Django 2.0.5 on 2018-06-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_hero_is_killed'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='defeats_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='wins_counter',
            field=models.IntegerField(default=0),
        ),
    ]
