# Generated by Django 2.0.5 on 2018-06-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20180604_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='defeats_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hero',
            name='wins_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
