# Generated by Django 2.0.5 on 2018-06-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20180604_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='murder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
