# Generated by Django 2.0.5 on 2018-06-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_hero_murder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='defeat_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
