# Generated by Django 2.0.5 on 2018-06-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_hero_defeat_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='hero_name',
            new_name='name',
        ),
    ]
