# Generated by Django 2.0.5 on 2018-06-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_auto_20180613_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_array', models.CharField(max_length=10000)),
            ],
        ),
    ]
