# Generated by Django 2.0.5 on 2018-06-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_pairingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairingmodel',
            name='hero1name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
