# Generated by Django 2.0.5 on 2018-06-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_pairingmodel_hero1name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pairingmodel',
            old_name='hero1name',
            new_name='first_hero',
        ),
        migrations.AddField(
            model_name='pairingmodel',
            name='group_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pairingmodel',
            name='second_hero',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
