# Generated by Django 2.0.5 on 2018-06-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_auto_20180617_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairingmodel',
            name='second_hero',
        ),
        migrations.AlterField(
            model_name='pairingmodel',
            name='first_hero',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
