# Generated by Django 2.0.5 on 2018-06-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_auto_20180617_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pairingmodel',
            old_name='first_hero',
            new_name='pairs',
        ),
    ]
