# Generated by Django 2.0.5 on 2018-06-18 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_auto_20180617_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='pairingmodel',
            name='interaction_array',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
