# Generated by Django 2.0.5 on 2018-06-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_auto_20180618_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
